packages:
  - packages/*
  - backend
publicHoistPattern:
  - "@types/node"
lockfileIncludeTarballUrl: false
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - miaoda-sc-plugin
  - miaoda-react-devkit
allowBuilds:
  esbuild: true
overrides:
  miaoda-react-devkit: workspace:*
