packages:
  - packages/*
  - backend
publicHoistPattern:
  - "@types/node"
lockfileIncludeTarballUrl: false
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - miaoda-sc-plugin
  - miaoda-react-devkit
allowBuilds:
  core-js: false
  esbuild: true
